trigger:
  branches:
    include:
      - develop

variables:
  FTP_SERVER: 'ftp.iipl.work'  # Replace with your FTP server address
  FTP_USERNAME: 'cyecom-qa@cyecomreactweb.iipl.work'  # Replace with your FTP username (set as a pipeline variable)
  FTP_PASSWORD: 'vYT$Hxf%x!]6'  # Replace with your FTP password (set as a pipeline variable)
  # FTP_REMOTE_DIR: '/home/hhs6zt8defml/cyecomreactweb.iipl.work'  # Replace with your FTP remote directory for the sub-domain
  FTP_REMOTE_DIR: '/public_html/cyecomreactweb.iipl.work'
  DOCKER_IMAGE_NAME: 'cyecom-react-ui'  # Replace with your Docker image name
  TAG: 'latest'
  vmImage: 'LocalServerAgent'
jobs:
- job: Build
  displayName: 'Build Docker Image'
  pool: $(vmImage)
  steps:
  - checkout: self

  # Add steps to build your project and create the Docker image

  - task: Docker@2
    displayName: 'Build Docker Image'
    inputs:
      command: build
      #containerRegistry: 'your-container-registry'  # Replace with your container registry connection
      repository: $(DOCKER_IMAGE_NAME)
      dockerfile: 'Dockerfile'
      tags: '$(TAG)'


- job: Deploy
  displayName: 'Deploy to GoDaddy FTP'
  dependsOn: Build
  pool: $(vmImage)
  steps:
  - checkout: self

  - script: |
      # Install the FTP deployment tool
      npm install -g ftp-deploy

      # Deploy the Docker image to the FTP server
      docker save $(DOCKER_IMAGE_NAME) | ftp-deploy --server $(FTP_SERVER) --user $(FTP_USERNAME) --password $(FTP_PASSWORD) --remote-dir $(FTP_REMOTE_DIR)/$(DOCKER_IMAGE_NAME).tar
    displayName: 'Deploy Docker Image to FTP'